twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'

when@test:
    twig:
        strict_variables: true
