index:
    path: /
    controller: App\Controller\PostController::index

post_add:
  path: /post/add
  controller: App\Controller\PostController::add

post_show:
  path: /post/show/{id}
  controller: App\Controller\PostController::show

post_edit:
  path: /post/edit/{id}
  controller: App\Controller\PostController::edit
  requirements:
    id: '\d+'
  
post_delete:
  path: /post/delete/{id}
  controller: App\Controller\PostController::delete
  requirements:
    id: '\d+'

# about
about:
  path: /about
  controller: App\Controller\PostController::about    


# prenium post
prenium:
    path: /prenium
    controller: App\Controller\PreniumPostController::prenium

prenium_post_add:
  path: /prenium_post/add
  controller: App\Controller\PreniumPostController::add

prenium_post_show:
  path: /prenium_post/show/{id}
  controller: App\Controller\PreniumPostController::show

prenium_post_edit:
  path: /prenium_post/edit/{id}
  controller: App\Controller\PreniumPostController::edit
  requirements:
    id: '\d+'
  
prenium_post_delete:
  path: /prenium_post/delete/{id}
  controller: App\Controller\PreniumPostController::delete
  requirements:
    id: '\d+'

prenium_pack:
    path: /prenium_pack
    controller: App\Controller\PreniumPostController::pack

# admin
admin:
  path: /admin
  controller:  App\Controller\AdminController::admin

# user
register:
  path: /register
  controller:  App\Controller\RegistrationController::register

login:
  path: /login
  controller:  App\Controller\SecurityController::login

logout:
  path: /logout
  controller:  App\Controller\LoginController::logout  

account:
  path: /account/{id}
  controller: App\Controller\UserController::account
  requirements:
    id: '\d+'

account_edit:
  path: /account/account_edit/{id}
  controller: App\Controller\UserController::edit
  requirements:
    id: '\d+'
  
account_delete:
  path: /account/account_delete/{id}
  controller: App\Controller\UserController::delete
  requirements:
    id: '\d+'

#cart_chekout
cart:
  path: /cart_checkout/cart
  controller: App\Controller\CheckoutController::cart

cart_add:
  path: /cart_checkout/cart_add/{id}
  controller: App\Controller\CheckoutController::add

cart_remove:
  path: /cart_checkout/cart_remove/{id}
  controller: App\Controller\CheckoutController::remove

cart_delete_all:
  path: /delete
  controller: App\Controller\CheckoutController::deleteAll

checkout_session:
  path: /checkout_session
  controller: App\Controller\CheckoutController::checkout
  requirements:
    id: '\d+'

checkout_success:
  path: /cart_checkout/checkout_success
  controller: App\Controller\CheckoutController::success

checkout_cancel:
  path: /cart_checkout/checkout_cancel
  controller: App\Controller\CheckoutController::cancel      